# For full config options, check the docs:
#    docs.serverless.com

service: care-corner-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java11
  lambdaHashingVersion: 20201221
  region: us-east-1
  environment:
    variable1: value1

package:
  artifact: 'target/${self:service}-${self:provider.stage}.jar'

functions:
  panic:
    handler: com.carecorner.PanicHandler
    events:
      - http:
          path: /api/panic
          method: post
plugins:
  - serverless-localstack

custom:
  bucket: care-corner-api
  localstack:
    stages:
      - local
    host: http://localstack
    edgePort: 4566
    debug: true
    lambda:
      mountCode: False
    docker:
      sudo: False

