# For full config options, check the docs:
#    docs.serverless.com

service: care-corner-api
frameworkVersion: '2'
#variablesResolutionMode: 20210219

provider:
  name: aws
  runtime: java11
  lambdaHashingVersion: 20201221
  region: us-east-1

package:
 # artifact: 'build/distributions/com.carecorner-${self:provider.stage}.zip'
 artifact: 'build/libs/care-corner-api-dev-all.jar'

functions:
  authentication:
    handler: com.carecorner.handler.AuthenticationHandler
    events:
      - http:
          path: /api/auth
          method: post
  contactGet:
    handler: com.carecorner.handler.contact.ContactHandler
    events:
      - http:
          path: /api/contacts/{id}
          method: get
  contactUpdate:
    handler: com.carecorner.handler.contact.UpdateHandler
    events:
      - http:
          path: /api/contacts
          method: put
  journeyBonVoyage:
      handler: com.carecorner.handler.journey.BonVoyageHandler
      events:
        - http:
            path: /api/journey
            method: post
  journeyWaypoint:
      handler: com.carecorner.handler.journey.WaypointHandler
      events:
        - http:
            path: /api/journey
            method: put
  journeyDestination:
      handler: com.carecorner.handler.journey.DestinationHandler
      events:
        - http:
            path: /api/journey/destination
            method: post

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localstack
    edgePort: 4566
    debug: true
    lambda:
      mountCode: False
    docker:
      sudo: False

