version: '3.9'
services:
  api:
    build: .
    container_name: care-corner-api
    depends_on:
      - localstack
      - database
    tty: true
    restart: always
    networks:
      docker_network:
        ipv4_address: 10.5.0.5
    volumes:
      - './serverless-api/:/care-corner-api'

  database:
    image: mysql:5.7
    container_name: care-corner-database
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: corner
      MYSQL_DATABASE: care-corner
      MYSQL_USER: care
      MYSQL_PASSWORD: corner
    volumes:
      - './mysql-data:/var/lib/mysql'
    networks:
      docker_network:
        ipv4_address: 10.5.0.6

  localstack:
    image: localstack/localstack:0.12.9.1
    container_name: care-corner-localstack
    restart: always
    ports:
      - '8080:8080'
      - '4566:4566'
    environment:
      - SERVICES= apigateway, lambda, s3, cloudformation, sts, iam, sns
      - DEFAULT_REGION=us-east-1
      - AWS_XRAY_SDK_ENABLED=true
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      docker_network:
        ipv4_address: 10.5.0.7

networks:
  docker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
